development:
  adapter: postgresql
  encoding: unicode
  database: breakout_machine_development
  pool: 25
  username: justinsilverman
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: breakout_machine_test
  pool: 5
  username: justinsilverman
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: breakout_machine_production
  pool: 25
  username: justinsilverman
  password:

